### basic settings

# site properties and page defaults
title: Kechris Lab
description: Website for group led by Katerina Kechris, at Colorado University, Anschutz Medical Campus, building of packages for multi-omics analysis, genetics
logo: images/kechrislogo.svg
header: images/dna-ancestry_2502064k.jpg
footer: images/dna-ancestry_2502064k.jpg
header-dark: false
footer-dark: false
baseurl: /KechrisLabWebsite

# site social media and other links
links:
  google-scholar: ywY1-w8AAAAJ&view_op=list_works&sortby=pubdate
  research-gate: Katerina-Kechris
  github: kechrislab
  
### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null

google_site_verification: eh7TTz_7qFUvyQ7RJ96UZdqorCsIRuxB6jNBkFQLX4I # your google-site-verification ID (Google Search Console) 
enable_google_verification: false  # enables google site verification 

