
- id: pmc:PMC8540572
  publisher: Metabolites. 11(10):678
  
- id: doi:10.1371/journal.pone.0255337
  publisher: PLoS One. 16:e0255337
  
- id: doi:10.1371/journal.pcbi.1008986
  publisher: PLoS Computational Biology.
  
- id: pmc:PMC8540572
  publisher: BMC Research Notes. 14(1):352
  
- id: doi: 10.1186/s12859-021-04336-9
  publisher: BMC Bioinformatics. 22(1):423
